### ISSUE TITLE
build doesn't work on macOS 

### ISSUE THREAD

**Issue by mrcnc** [boundlessgeo/schema#47]
The `dirname` command doesn't work the same for bash on macOS so we're not able to compile all of the source files. 
```
$ sh script/java.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
script/java.sh: line 23: ./index.sh: No such file or directory
```

This is a "nice to have" b/c Jenkins should be building and publishing these artifacts anyway

**Comment by joshkendrick** [comment]
this WOMM (works on my mac) as of https://github.com/boundlessgeo/schema/pull/51
